spring:
  application:
    name:rest-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ferpatestedb?useTimezone=true&serverTimezone=UTC
    username: root
    password: master
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          #dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enable: true
      file-size-threshold: 2k
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    root: WARN
    #com.ferpateste: DEBUG



